// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentMangementsystem.Data;

#nullable disable

namespace RentMangementsystem.Migrations
{
    [DbContext(typeof(RentManagementContext))]
    partial class RentManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentMangementsystem.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ElectricAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ElectricMeterReadingId")
                        .HasColumnType("int");

                    b.Property<decimal>("MiscAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RentAgreementId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ElectricMeterReadingId");

                    b.HasIndex("RentAgreementId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TenantId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("RentMangementsystem.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("RentMangementsystem.Models.ElectricMeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentReading")
                        .HasColumnType("int");

                    b.Property<decimal>("ElectricCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsBilled")
                        .HasColumnType("bit");

                    b.Property<int>("PreviousReading")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreviousReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("ElectricMeterReadings");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RentAgreementId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("RentAgreementId");

                    b.HasIndex("TenantId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasLaundryFacility")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSharedBathrooms")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSharedKitchen")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWiFi")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Your Property Address",
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4387),
                            Description = "22-room boarding house with 3 floors - Ground floor (10 rooms), First floor (6 rooms), Second floor (6 rooms)",
                            HasLaundryFacility = true,
                            HasParking = false,
                            HasSharedBathrooms = true,
                            HasSharedKitchen = true,
                            HasWiFi = true,
                            NumberOfFloors = 3,
                            PropertyName = "Your Boarding House Name",
                            PropertyType = "Boarding House",
                            TotalArea = 1000m,
                            TotalRooms = 22
                        });
                });

            modelBuilder.Entity("RentMangementsystem.Models.RentAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgreementType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("SecurityDeposit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Terms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TenantId");

                    b.ToTable("RentAgreements");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ElectricMeterNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("HasAC")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPrivateBathroom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("bit");

                    b.Property<int?>("LastMeterReading")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4656),
                            ElectricMeterNumber = "GM001",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1050,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4653),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/1",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4661),
                            ElectricMeterNumber = "GM002",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1100,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4661),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/2",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 3,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4665),
                            ElectricMeterNumber = "GM003",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1150,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4665),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/3",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 4,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4670),
                            ElectricMeterNumber = "GM004",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1200,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4669),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/4",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 5,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4674),
                            ElectricMeterNumber = "GM005",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1250,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4673),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/5",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 6,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4679),
                            ElectricMeterNumber = "GM006",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1300,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4678),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/6",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 7,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4682),
                            ElectricMeterNumber = "GM007",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1350,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4682),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/7",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 8,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4719),
                            ElectricMeterNumber = "GM008",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1400,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4718),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/8",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 9,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4722),
                            ElectricMeterNumber = "GM009",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1450,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4722),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/9",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 10,
                            Area = 120m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4729),
                            ElectricMeterNumber = "GM010",
                            Floor = "Ground",
                            FloorNumber = 0,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1500,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4729),
                            MonthlyRent = 500.00m,
                            PropertyId = 1,
                            RoomNumber = "G/10",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 11,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4738),
                            ElectricMeterNumber = "F1M001",
                            Floor = "First",
                            FloorNumber = 1,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1260,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4737),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "1/1",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 12,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4742),
                            ElectricMeterNumber = "F1M002",
                            Floor = "First",
                            FloorNumber = 1,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1320,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4742),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "1/2",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 13,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4745),
                            ElectricMeterNumber = "F1M003",
                            Floor = "First",
                            FloorNumber = 1,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1380,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4745),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "1/3",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 14,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4749),
                            ElectricMeterNumber = "F1M004",
                            Floor = "First",
                            FloorNumber = 1,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1440,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4748),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "1/4",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 15,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4752),
                            ElectricMeterNumber = "F1M005",
                            Floor = "First",
                            FloorNumber = 1,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1500,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4751),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "1/5",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 16,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4755),
                            ElectricMeterNumber = "F1M006",
                            Floor = "First",
                            FloorNumber = 1,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1560,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4754),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "1/6",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 17,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4761),
                            ElectricMeterNumber = "F2M001",
                            Floor = "Second",
                            FloorNumber = 2,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1470,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4760),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "2/1",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 18,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4765),
                            ElectricMeterNumber = "F2M002",
                            Floor = "Second",
                            FloorNumber = 2,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1540,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4765),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "2/2",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 19,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4769),
                            ElectricMeterNumber = "F2M003",
                            Floor = "Second",
                            FloorNumber = 2,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1610,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4768),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "2/3",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 20,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4771),
                            ElectricMeterNumber = "F2M004",
                            Floor = "Second",
                            FloorNumber = 2,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1680,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4771),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "2/4",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 21,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4774),
                            ElectricMeterNumber = "F2M005",
                            Floor = "Second",
                            FloorNumber = 2,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1750,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4774),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "2/5",
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 22,
                            Area = 130m,
                            CreatedDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4777),
                            ElectricMeterNumber = "F2M006",
                            Floor = "Second",
                            FloorNumber = 2,
                            HasAC = false,
                            HasPrivateBathroom = false,
                            IsAvailable = true,
                            IsFurnished = false,
                            LastMeterReading = 1820,
                            LastReadingDate = new DateTime(2025, 7, 12, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4777),
                            MonthlyRent = 550.00m,
                            PropertyId = 1,
                            RoomNumber = "2/6",
                            RoomType = "Single"
                        });
                });

            modelBuilder.Entity("RentMangementsystem.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electric",
                            ConfigKey = "ElectricUnitCost",
                            ConfigValue = "12.00",
                            Description = "Cost per electric unit in currency",
                            LastUpdated = new DateTime(2025, 8, 11, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4578)
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            ConfigKey = "PropertyName",
                            ConfigValue = "Your Boarding House",
                            Description = "Name of the property",
                            LastUpdated = new DateTime(2025, 8, 11, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4581)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Billing",
                            ConfigKey = "BillDueDays",
                            ConfigValue = "15",
                            Description = "Number of days for bill due date",
                            LastUpdated = new DateTime(2025, 8, 11, 12, 26, 6, 386, DateTimeKind.Local).AddTicks(4585)
                        });
                });

            modelBuilder.Entity("RentMangementsystem.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Bill", b =>
                {
                    b.HasOne("RentMangementsystem.Models.ElectricMeterReading", "ElectricMeterReading")
                        .WithMany("Bills")
                        .HasForeignKey("ElectricMeterReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentMangementsystem.Models.RentAgreement", "RentAgreement")
                        .WithMany()
                        .HasForeignKey("RentAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentMangementsystem.Models.Room", "Room")
                        .WithMany("Bills")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentMangementsystem.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ElectricMeterReading");

                    b.Navigation("RentAgreement");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentMangementsystem.Models.BillItem", b =>
                {
                    b.HasOne("RentMangementsystem.Models.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("RentMangementsystem.Models.ElectricMeterReading", b =>
                {
                    b.HasOne("RentMangementsystem.Models.Room", "Room")
                        .WithMany("ElectricMeterReadings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Payment", b =>
                {
                    b.HasOne("RentMangementsystem.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentMangementsystem.Models.RentAgreement", "RentAgreement")
                        .WithMany("Payments")
                        .HasForeignKey("RentAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentMangementsystem.Models.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("RentAgreement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentMangementsystem.Models.RentAgreement", b =>
                {
                    b.HasOne("RentMangementsystem.Models.Property", "Property")
                        .WithMany("RentAgreements")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentMangementsystem.Models.Room", "Room")
                        .WithMany("RentAgreements")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentMangementsystem.Models.Tenant", "Tenant")
                        .WithMany("RentAgreements")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Room", b =>
                {
                    b.HasOne("RentMangementsystem.Models.Property", "Property")
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Bill", b =>
                {
                    b.Navigation("BillItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RentMangementsystem.Models.ElectricMeterReading", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Property", b =>
                {
                    b.Navigation("RentAgreements");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RentMangementsystem.Models.RentAgreement", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Room", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("ElectricMeterReadings");

                    b.Navigation("RentAgreements");
                });

            modelBuilder.Entity("RentMangementsystem.Models.Tenant", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("RentAgreements");
                });
#pragma warning restore 612, 618
        }
    }
}
